<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>742d5282-44e7-48da-bb63-bf071db4724e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" Version="15.1.11" />
    <PackageReference Include="HotChocolate.Fusion" Version="15.1.11" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="gateway.fgp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
