<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-BackOfficeService-a23d8ebe-5189-49d2-9759-5b66ee4ea18c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" Version="8.16.4" />
    <PackageReference Include="WolverineFx" Version="5.7.1" />
    <PackageReference Include="WolverineFx.Marten" Version="5.7.1" />
    <PackageReference Include="WolverineFx.Postgresql" Version="5.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
</Project>
